services:
  - type: web
    name: darkhole
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1 --threads 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: GUNICORN_CMD_ARGS
        value: "--timeout 120 --workers 1 --threads 2" 